FROM nginx:alpine

COPY russia_ip_ranges.txt /tmp/
RUN sed 's/$/ 1;/' /tmp/russia_ip_ranges.txt > /etc/nginx/russia_ip_ranges.txt

COPY nginx.conf /etc/nginx/nginx.conf
COPY blocked.html /usr/share/nginx/html/blocked.html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]