FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY blocked.html /usr/share/nginx/html/blocked.html
COPY russia_ip_ranges.txt /etc/nginx/russia_ip_ranges.txt

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]